Repository liveblog/liveblog, pull requests merged in 2018-04, with the labels that each got.

#1120 feature: added `register_theme` and `register_freetype` commands
  server/liveblog/freetypes/__init__.py
  server/liveblog/freetypes/commands.py
  server/liveblog/freetypes/freetypes.py
  server/liveblog/themes/__init__.py
  server/liveblog/themes/commands.py
  server/liveblog/themes/themes.py
Labels: need reviews

#1124 feature: allow unpublished posts in contributions.
  client/app/scripts/liveblog-edit/posts.service.js
Labels: need reviews

#1126 Test case/client modules
  server/liveblog/client_modules/client_modules.py
  server/liveblog/client_modules/client_modules_test.py
Labels: need reviews

#1130 Serbian localization update
  server/liveblog/themes/themes_assets/classic/dist/scripts.min.js
  server/liveblog/themes/themes_assets/classic/dist/translations.js
  server/liveblog/themes/themes_assets/classic/po/classic.sr-cy.po
  server/liveblog/themes/themes_assets/classic/po/classic.sr.po
  server/liveblog/themes/themes_assets/classic/theme.json
  server/liveblog/themes/themes_assets/default/dist/default-3a82ccc51d.js
  server/liveblog/themes/themes_assets/default/dist/default-4b7daf285e.js
  server/liveblog/themes/themes_assets/default/dist/rev-manifest.json
  server/liveblog/themes/themes_assets/default/package.json
  server/liveblog/themes/themes_assets/default/theme.json
Labels: wip

#1136 fix: remove unneeded files.
  .travis.yml
  classic.js
  dist/default-818e782fed.js
  dist/default-d5029b1015.js
  dist/default-ee222428a2.css
  dist/default-f2682b7ad6.css
  dist/scripts.min.js
  server/liveblog/themes/themes.py
Labels: need reviews, wip

#1134 fix: fixed classic theme slideshow issue
  server/liveblog/themes/themes_assets/classic/views/posts.html
Labels: need reviews

#1128 Test case/items languages modules
  server/liveblog/items/items.py
  server/liveblog/items/items_test.py
  server/liveblog/languages/languages.py
  server/liveblog/languages/languages_test.py
Labels: need reviews

#1121 Feature/amp commenting
  server/liveblog/blogs/embeds.py
  server/liveblog/blogs/templates/embed_amp.html
  server/liveblog/client_modules/client_modules.py
  server/liveblog/themes/themes_assets/amp/dist/amp-e2571df984.css
  server/liveblog/themes/themes_assets/amp/less/embed.less
  server/liveblog/themes/themes_assets/amp/template.html
  server/liveblog/themes/themes_assets/amp/templates/template-comment.html
  server/liveblog/themes/themes_assets/amp/templates/template-index.html
  server/liveblog/themes/themes_assets/amp/templates/template-timeline.html
  server/liveblog/themes/themes_assets/amp/test/options.json
  server/liveblog/themes/themes_assets/amp/theme.json
  server/settings.py
Labels: need reviews

#1127 Test case/blogs modules
  server/liveblog/blogs/blog.py
  server/liveblog/blogs/blog_test.py
  server/liveblog/blogs/blogs.py
  server/liveblog/blogs/blogs_test.py
  server/liveblog/blogs/embeds.py
  server/liveblog/test_theme_settings.py
  server/liveblog/themes/test_theme_settings.py
  server/liveblog/themes/themes.py
Labels: need reviews
